services:
  - type: web
    name: hyperhire-tinder-be
    env: php
    buildCommand: 
      - "./build.sh"
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: hyperhire_db
          property:hostname
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        fromDatabase:
          name: hyperhire_db
          property:database
      - key: DB_USERNAME
        fromDatabase:
          name: hyperhire_db
          property:user
      - key: DB_PASSWORD
        fromDatabase:
          name: hyperhire_db
          property:password
    autoDeploy: true
databases:
  - name: hyperhire_db
    databaseName: hyperhire_php_tinder_be
    user: hyperhire_user